stages:
  - precommit
  - build
  - test
  - docker

precommit:
  stage: precommit
  script:
    - python -m pre_commit run --all-files

compile:
  stage: build
  needs: [precommit]
  script:
    - javac Main.java

test:
  stage: test
  needs: [compile]
  script:
    - java Main

docker-build:
  stage: docker
  needs: [test]
  script:
    - docker build -t compteurclic .
